### ISSUE TITLE
Release version with updated NMRium

### ISSUE THREAD

**Issue by stropitek** [zakodium/c6h6-react#26]

**Comment by stropitek** [comment]
@targos do you want to take this or should I assign myself?

**Comment by targos** [comment]
I may take it but probably not this week.

**Comment by targos** [comment]
I put the new version on https://my.cheminfo.org/on-tabs/

**Comment by stropitek** [comment]
There are two versions of this tool on https://my.cheminfo.org/on-tabs/

One in dev tab, it seems to use an outdated version of HEAD 

The other in NMR tab, it uses v1.1.2

**Comment by targos** [comment]
It's the "Analyse NMR" tile on this tab

![image](https://user-images.githubusercontent.com/2352663/159002763-de477db6-e6b0-4d92-a1a2-931d69e2f395.png)

**Comment by targos** [comment]
And you're right, it's still on v1.1.2. It seems my save wasn't committed.

**Comment by stropitek** [comment]
ok, figured out that you the config is no longer saved in the view itself, you have to hit the save button the view has

Is the HEAD build support dropped? Because the other tile in dev loads an outdated version I think (page still hangs when you make a range picking that is too large)

**Comment by targos** [comment]
the HEAD build needs to be manually triggered at https://github.com/zakodium/c6h6-react/actions/workflows/publish-head.yml
